name: GitHub metrics
on:
#  schedule:
#    - cron: "21 6,18 * * *"  # Runs at 6:21 AM and 6:21 PM UTC daily
  workflow_dispatch:
jobs:

  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: Personal metrics
        uses: JayantGoel001/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity, community, repositories"
          
          # Plugin Configurations
          plugin_introduction: yes  # Show personal introduction
          plugin_isocalendar: yes  # Show isocalendar activity (contribution streaks)
          plugin_isocalendar_duration: full-year  # Display full-year streaks
          plugin_habits: yes  # Show developer habits (e.g., daily activity patterns)
          plugin_habits_from: 200  # Data from last 200 contributions
          plugin_habits_facts: yes  # Display interesting facts
          plugin_habits_charts: yes  # Show activity charts

          # Repository and Contribution Details
          plugin_stars: yes  # Show top repos based on stars
          plugin_stars_limit: 4  # Limit to top 4 repos
          plugin_activity: yes  # Show activity in repositories
          plugin_activity_limit: 5  # Limit to 5 most recent activities
          plugin_activity_days: 14  # Limit activity to the last 14 days

          plugin_achievements: yes  # Show achievements like milestone completions
          plugin_achievements_threshold: C  # Minimum threshold for achievement display
          plugin_achievements_display: compact  # Display compact achievements

          # Miscellaneous Plugins
          plugin_notable: yes  # Highlight notable achievements and contributions
          plugin_tweets_attachments: yes  # Show recent tweets with attachments
          plugin_fortune: yes  # Show a random fortune message
          plugin_sponsors: yes  # Display GitHub Sponsors section
          plugin_sponsors_sections: goal, list, about  # Configure sponsor sections

          # Additional settings
          config_timezone: Asia/Kolkata  # Set timezone to your local timezone

  github-metrics-detailed-personal:
    runs-on: ubuntu-latest
    steps:
      - name: Detailed personal metrics
        uses: JayantGoel001/metrics@master
        with:
          filename: metrics.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "metadata"

          # Advanced Plugin Configurations
          plugin_gists: yes  # Show gists contributed to
          plugin_pagespeed: yes  # Display Pagespeed insights
          plugin_pagespeed_detailed: yes  # Show detailed Pagespeed insights
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}  # Token for Pagespeed API
          plugin_pagespeed_screenshot: yes  # Include screenshot of Pagespeed report
          plugin_pagespeed_pwa: yes  # Show PWA (Progressive Web App) score

          plugin_followup: yes  # Show follow-up on repositories and user activity
          plugin_followup_sections: repositories, user  # Configure follow-up sections
          plugin_followup_indepth: yes  # Show in-depth follow-up details

          plugin_languages: yes  # Show programming languages breakdown
          plugin_languages_colors: "rainbow"  # Display in rainbow colors
          plugin_languages_details: bytes-size, percentage  # Show both byte size and percentage usage

          plugin_posts: yes  # Show dev.to posts
          plugin_posts_source: dev.to  # Source for posts
          plugin_posts_limit: 2  # Limit to 2 most recent posts
          plugin_posts_user: JayantGoel001  # Customize with your dev.to username
          plugin_posts_descriptions: yes  # Show post descriptions
          plugin_posts_covers: yes  # Show post cover images

          config_timezone: Asia/Kolkata  # Set timezone to your local timezone
