name: Generate 3D Profile

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate the regular snake graph (optional)
      - name: Generate snake.svg (optional)
        uses: Platane/snk@v3
        with:
          github_user_name: IamRam3
          outputs: |
            ./github-contribution-grid-snake.svg

      # Step 2: Generate the 3D Profile Graph
      - name: Generate 3D Profile Contribution Graph
        uses: Platane/snk@v3
        with:
          github_user_name: IamRam3
          outputs: |
            ./profile-3d-contrib/profile-night-rainbow.svg

      # Step 3: Initialize Git repository and commit the 3D Profile SVG
      - name: Commit and push 3D Profile SVG to the output branch
        run: |
          # Initialize a git repository if not already initialized
          git init
          
          # Set the user name and email for the commit
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Add the 'profile-3d-contrib' directory if it doesn't exist
          mkdir -p profile-3d-contrib
          
          # Stage the generated 3D profile SVG file
          git add profile-3d-contrib/profile-night-rainbow.svg

          # Commit the changes
          git commit -m "Add 3D profile contribution graph"

          # Set the remote for the output branch (this step ensures you can push)
          git remote add origin https://github.com/${{ github.repository }}.git
          
          # Push the changes to the output branch
          git push origin HEAD:output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
