name: Generate Snake Contributions

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: IamRam3
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Commit and push snake.svg to the output branch
        run: |
          git init
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add github-contribution-grid-snake.svg
          git commit -m "Add snake contribution graph"

          git branch -M output
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push --force origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
