name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate the regular snake graph
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: IamRam3
          outputs: |
            ./github-contribution-grid-snake.svg

      # Step 2: Generate the 3D profile graph
      - name: Generate 3D Profile Snake
        uses: Platane/snk@v3
        with:
          github_user_name: IamRam3
          outputs: |
            ./profile-3d-contrib/profile-night-rainbow.svg

      # Step 3: Push both the snake.svg and profile-3d SVG to the output branch
      - name: Push SVGs to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .  # Include all files, adjust path if necessary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
