name: Generate 3D Profile

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate the regular snake graph (this step can be kept if you still want it)
      - name: Generate snake.svg (optional)
        uses: Platane/snk@v3
        with:
          github_user_name: IamRam3
          outputs: |
            ./github-contribution-grid-snake.svg

      # Step 2: Generate the 3D Profile Graph
      - name: Generate 3D Profile Contribution Graph
        uses: Platane/snk@v3
        with:
          github_user_name: IamRam3
          outputs: |
            ./profile-3d-contrib/profile-night-rainbow.svg

      # Step 3: Commit and push the 3D profile SVG to the output branch
      - name: Commit and push 3D Profile SVG to the output branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Create the 'profile-3d-contrib' directory if it doesn't exist
          mkdir -p profile-3d-contrib
          
          # Add the generated 3D profile graph file
          git add profile-3d-contrib/profile-night-rainbow.svg

          # Commit the changes
          git commit -m "Add 3D profile contribution graph"

          # Push the changes to the output branch
          git push origin HEAD:output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
