name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: WakaTime README Stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_USERNAME: "IamRam3"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TIMEZONE: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_OS: "True"
          SHOW_LOC_CHART: "False"
          SHOW_SHORT_INFO: "True"
